# Generated by Django 5.0.6 on 2024-10-05 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_orderitem_product'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
