# Generated by Django 5.0.6 on 2024-10-05 14:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2147483647)])),
                ('description', models.TextField(max_length=400, validators=[django.core.validators.MinLengthValidator(4, 'Mínimo de 4 caracteres.')])),
                ('stock', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2147483647)])),
                ('archived', models.BooleanField(default=False)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='product.productcategory')),
            ],
        ),
    ]
