# Generated by Django 5.0.6 on 2024-10-05 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_orderitem_product'),
        ('product', '0003_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
