# Generated by Django 5.0.6 on 2024-10-17 14:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_delete_product_delete_productcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.SlugField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2147483647)])),
                ('description', models.TextField(max_length=400, validators=[django.core.validators.MinLengthValidator(4, 'Mínimo de 4 caracteres.')])),
                ('stock', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2147483647)])),
                ('archived', models.BooleanField(default=False)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('combo', models.BooleanField(default=False)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='product.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(help_text='Ex.: Pequena, Média, Grande, 2l, 200ml', max_length=40)),
                ('short_size_name', models.CharField(blank=True, help_text='Opcional. Ex.: P, M, G', max_length=5, null=True)),
                ('diameter', models.PositiveSmallIntegerField(help_text='Em centimetros', validators=[django.core.validators.MaxValueValidator(32767)])),
                ('price', models.PositiveIntegerField(help_text='Em inteiro. Ex.: 4999 para representar R$ 49,99', validators=[django.core.validators.MaxValueValidator(2147483647)])),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, help_text='Em decimal. Ex.: 0.1 para representar 10%. 0.0 quando não há desconto.', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('stock', models.PositiveIntegerField(blank=True, help_text='Opcional. Se não for preenchido, o estoque será ilimitado para pedidos. 0 representa que o estoque está vazio.', null=True, validators=[django.core.validators.MaxValueValidator(2147483647)])),
                ('stuffed_edge', models.BooleanField(default=True)),
                ('archived', models.BooleanField(default=True)),
                ('default', models.BooleanField(default=False, help_text='A variante que representará a pizza e será mostrada no site. Se não houver uma variante padrão a primeira variante registrada será mostrada no site. Se existir duas ou mais variantes padrões a primeira variante registrada e marcada como padrão será mostrada no site.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': 'Variante de pizza',
                'verbose_name_plural': 'Variantes de pizza',
            },
        ),
    ]
