# Generated by Django 5.0.6 on 2024-10-17 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productcategory_product_productvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
