# Generated by Django 5.0.6 on 2024-10-17 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_orderitem_pizza_remove_orderitem_soda_and_more'),
        ('product', '0006_remove_product_archived_remove_product_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzavariant',
            name='pizza',
        ),
        migrations.RemoveField(
            model_name='sodavariant',
            name='soda',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'verbose_name': 'Variante do produto', 'verbose_name_plural': 'Variantes do produto'},
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='default',
            field=models.BooleanField(default=False, help_text='A variante que representará o produto no site.'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='diameter',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Em centimetros', null=True, validators=[django.core.validators.MaxValueValidator(32767)]),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stuffed_edge',
            field=models.BooleanField(blank=True, choices=[(None, 'Sem borda'), (True, 'Sim'), (False, 'Não')], null=True),
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='PizzaVariant',
        ),
        migrations.DeleteModel(
            name='Soda',
        ),
        migrations.DeleteModel(
            name='SodaVariant',
        ),
    ]
