# Generated by Django 5.0.6 on 2024-10-17 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_combo_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comboitem',
            name='product',
        ),
        migrations.AddField(
            model_name='comboitem',
            name='product_variant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.productvariant'),
            preserve_default=False,
        ),
    ]
