# Generated by Django 5.0.6 on 2024-10-23 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_comboitem_product_comboitem_product_variant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={},
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='code',
        ),
    ]
