# Generated by Django 5.0.6 on 2024-10-23 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_productcategory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='combo',
        ),
    ]
