# Generated by Django 5.0.6 on 2024-10-24 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_remove_product_combo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategory',
            new_name='Category',
        ),
    ]
