# Generated by Django 5.0.6 on 2024-10-24 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_rename_productcategory_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_category',
            new_name='category',
        ),
    ]
