# Generated by Django 5.0.6 on 2024-10-28 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_category_options_combo_archived'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'produto', 'verbose_name_plural': 'produtos'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'verbose_name': 'variante do produto', 'verbose_name_plural': 'variantes do produto'},
        ),
    ]
