# Generated by Django 5.0.6 on 2024-11-11 17:58

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='image',
            field=models.ImageField(default='', storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/home/vboxuser/projects/django-project/netdelivery/media')), upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/home/vboxuser/projects/django-project/netdelivery/media')), upload_to=''),
        ),
    ]
