# Generated by Django 5.0.6 on 2024-11-11 18:12

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_combo_image_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='image',
            field=models.ImageField(help_text='Add square images, with 1:1 dimension.', storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/home/vboxuser/projects/django-project/netdelivery/media')), upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(help_text='Add square images, with 1:1 dimension.', storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/home/vboxuser/projects/django-project/netdelivery/media')), upload_to=''),
        ),
    ]
