# Generated by Django 5.0.6 on 2024-12-07 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_comboitem_combo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comboitem',
            name='combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.combo'),
        ),
        migrations.AlterField(
            model_name='comboitem',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productvariant'),
        ),
    ]
