# Generated by Django 5.0.6 on 2024-12-07 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_product_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comboitem',
            name='combo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.combo'),
            preserve_default=False,
        ),
    ]
