# Generated by Django 5.0.6 on 2024-12-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_combo_user_alter_comboitem_combo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
