# Generated by Django 5.0.6 on 2024-12-12 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_alter_productvariant_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='short_size_name',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='size_name',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='milliliters',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Em centimetros', null=True, validators=[django.core.validators.MaxValueValidator(32767)]),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='size',
            field=models.CharField(blank=True, choices=[('1', 'Pequena'), ('2', 'Média'), ('3', 'Grande'), ('4', 'Gigante'), ('5', 'Família'), ('6', 'Maracanã')], max_length=40, null=True),
        ),
    ]
