# Generated by Django 5.0.6 on 2024-12-12 17:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_remove_productvariant_short_size_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='default',
            field=models.BooleanField(default=False, help_text='A variante que representará o produto no site.', verbose_name='Default'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='diameter',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Em centimetros', null=True, validators=[django.core.validators.MaxValueValidator(32767)], verbose_name='Diameter'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Em decimal. Ex.: 0.1 para representar 10%. 0.0 quando não há desconto.', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='milliliters',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Em centimetros', null=True, validators=[django.core.validators.MaxValueValidator(32767)], verbose_name='Milliliters'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.PositiveIntegerField(help_text='Em inteiro. Ex.: 4999 para representar R$ 49,99', validators=[django.core.validators.MaxValueValidator(2147483647)], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(blank=True, choices=[('1', 'Pequena'), ('2', 'Média'), ('3', 'Grande'), ('4', 'Gigante'), ('5', 'Família'), ('6', 'Maracanã')], max_length=40, null=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.PositiveIntegerField(blank=True, help_text='Opcional. Se não for preenchido, o estoque será ilimitado para pedidos. 0 representa que o estoque está vazio.', null=True, validators=[django.core.validators.MaxValueValidator(2147483647)], verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stuffed_edge',
            field=models.BooleanField(blank=True, choices=[(None, 'Sem borda'), (True, 'Sim'), (False, 'Não')], null=True, verbose_name='Stuffed Edge'),
        ),
    ]
