# Generated by Django 5.0.6 on 2024-12-12 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_alter_productvariant_archived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('1', 'Pizza salgada'), ('2', 'Pizza doce'), ('3', 'Pizza vegetariana'), ('4', 'Pizza mista'), ('5', 'Cachorro-Quente'), ('6', 'Sanduíche'), ('7', 'Salgado frito'), ('8', 'Salgado assado'), ('9', 'Empanada'), ('10', 'Batata Frita'), ('11', 'Nugget'), ('12', 'Pastel'), ('13', 'Refrigerante'), ('14', 'Suco'), ('15', 'Milkshake')], max_length=20, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='milliliters',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(32767)], verbose_name='Milliliters'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
