# Generated by Django 5.0.6 on 2024-12-13 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='complements',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(32767)], verbose_name='Complements'),
        ),
    ]
