# Generated by Django 5.0.6 on 2024-12-13 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_productvariant_complements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='complements',
        ),
    ]
