# Generated by Django 5.0.6 on 2024-12-13 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=600, validators=[django.core.validators.MinLengthValidator(4, 'Mínimo de 4 caracteres.')]),
        ),
    ]
