# Generated by Django 5.0.6 on 2024-12-20 19:33

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='image',
            field=models.ImageField(help_text='Add square images, with 1:1 dimension.', storage=django.core.files.storage.FileSystemStorage(location=''), upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(help_text='Add square images, with 1:1 dimension.', storage=django.core.files.storage.FileSystemStorage(location=''), upload_to=''),
        ),
    ]
