# Generated by Django 5.0.6 on 2024-12-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_alter_combo_image_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(help_text='Add square images, with 1:1 dimension.', upload_to=''),
        ),
    ]
