# Generated by Django 5.0.6 on 2024-12-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
