# Generated by Django 5.0.6 on 2025-01-04 15:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_alter_combo_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comboitem',
            options={'verbose_name': 'combo item', 'verbose_name_plural': 'combo items'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='archived'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='description',
            field=models.TextField(max_length=400, validators=[django.core.validators.MinLengthValidator(4, 'Minimum of 4 characters.')], verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='In decimal. Ex.: 0.1 to represent 10%. 0.0 when there is no discount.', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2147483647)], verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='comboitem',
            name='combo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.combo', verbose_name='combo'),
        ),
        migrations.AlterField(
            model_name='comboitem',
            name='product_variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productvariant', verbose_name='product variant'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='product.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=600, validators=[django.core.validators.MinLengthValidator(4, 'Minimum of 4 characters.')], verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='archived'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='default',
            field=models.BooleanField(default=False, help_text='The variant that will represent the product on the website.', verbose_name='default'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='diameter',
            field=models.PositiveSmallIntegerField(blank=True, help_text='In centimeters', null=True, validators=[django.core.validators.MaxValueValidator(32767)], verbose_name='diameter'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='In decimal. Ex.: 0.1 to represent 10%. 0.0 when there is no discount.', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='milliliters',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(32767)], verbose_name='milliliters'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2147483647)], verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(blank=True, choices=[('1', 'Small'), ('2', 'Medium'), ('3', 'Large'), ('4', 'Giant'), ('5', 'Family'), ('6', 'Maracanã')], max_length=40, null=True, verbose_name='size'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.PositiveIntegerField(blank=True, help_text='Optional. If left blank, stock will be unlimited for orders. 0 represents that stock is empty.', null=True, validators=[django.core.validators.MaxValueValidator(2147483647)], verbose_name='stock'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stuffed_edge',
            field=models.BooleanField(blank=True, choices=[(None, 'Sem borda'), (True, 'Sim'), (False, 'Não')], null=True, verbose_name='stuffed edge'),
        ),
    ]
