# Generated by Django 5.0.6 on 2025-05-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_alter_comboitem_options_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='product_fields',
            field=models.CharField(default='', max_length=120, verbose_name='product fields'),
            preserve_default=False,
        ),
    ]
