# Generated by Django 5.0.6 on 2025-05-24 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_category_product_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='product_fields',
        ),
    ]
