# Generated by Django 5.0.6 on 2025-05-24 19:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_remove_category_product_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='diameter',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='milliliters',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='size',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='stuffed_edge',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='note',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=400, validators=[django.core.validators.MinLengthValidator(4, 'Minimum of 4 characters.')], verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.CreateModel(
            name='OptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('0', 'Single'), ('1', 'Multiple')], default='1', max_length=10, verbose_name='type')),
                ('minimum', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='minimum')),
                ('product_variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.productvariant', verbose_name='variant')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=15, verbose_name='option')),
                ('price', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(32767)], verbose_name='price')),
                ('option_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.optiongroup', verbose_name='option group')),
            ],
        ),
    ]
