# Generated by Django 5.0.6 on 2025-05-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0043_remove_productvariant_diameter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='option',
        ),
        migrations.AddField(
            model_name='option',
            name='name',
            field=models.CharField(default='', max_length=15, verbose_name='name'),
            preserve_default=False,
        ),
    ]
