# Generated by Django 5.0.6 on 2025-05-25 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_remove_option_option_option_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.optiongroup', verbose_name='option group'),
        ),
        migrations.AlterField(
            model_name='optiongroup',
            name='type',
            field=models.CharField(choices=[('0', 'Single choice'), ('1', 'Multiple choices')], default='1', max_length=10, verbose_name='type'),
        ),
    ]
