# Generated by Django 5.0.6 on 2025-05-25 19:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0045_alter_option_option_group_alter_optiongroup_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='optiongroup',
            name='maximum',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='maximum'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='optiongroup',
            name='minimum',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='minimum'),
        ),
    ]
