# Generated by Django 5.0.6 on 2025-05-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0046_optiongroup_maximum_alter_optiongroup_minimum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='note',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='note'),
        ),
    ]
