# Generated by Django 5.0.6 on 2024-07-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='code',
            field=models.CharField(default='code', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
