# Generated by Django 5.0.6 on 2024-07-23 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_paymenttype_shippingtax_alter_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.orderstatus'),
        ),
    ]
