# Generated by Django 5.0.6 on 2024-07-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_orderstatus_code_alter_orderstatus_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='received_date',
            field=models.DateTimeField(null=True),
        ),
    ]
