# Generated by Django 5.0.6 on 2024-07-23 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_orderstatus_orderitem_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, to='core.orderstatus'),
        ),
    ]
