# Generated by Django 5.0.6 on 2024-07-30 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_received_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order_status',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='core.orderstatus'),
        ),
    ]
