# Generated by Django 5.0.6 on 2024-07-23 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_orderitem_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.orderstatus'),
        ),
    ]
