# Generated by Django 5.0.6 on 2024-08-23 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_shipping_tax_order_shipping_fee_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='shippingfee',
        #     name='name',
        # ),
        # migrations.AddField(
        #     model_name='shippingfee',
        #     name='bairro',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bairro'),
        # ),
        migrations.AddField(
            model_name='shippingfee',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Default'),
        ),
    ]
