# Generated by Django 5.0.6 on 2024-07-23 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_orderitem_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='core.orderstatus'),
        ),
    ]
