# Generated by Django 5.0.6 on 2024-07-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_paymenttype_code_alter_orderitem_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttype',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
