# Generated by Django 5.0.6 on 2024-07-30 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_order_status_orderitem_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderStatus',
            new_name='OrderItemStatus',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='status',
            new_name='order_item_status',
        ),
    ]
