# Generated by Django 5.0.6 on 2024-08-23 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_shippingfee_name_shippingfee_bairro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingfee',
            options={'verbose_name': 'Shipping fee', 'verbose_name_plural': 'Shipping fees'},
        ),
    ]
