# Generated by Django 5.0.6 on 2024-07-23 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_paymenttype_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.shippingtax'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_tax_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_tax_value',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
