# Generated by Django 5.0.6 on 2024-08-02 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_orderstatus_orderitemstatus_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Order item', 'verbose_name_plural': 'Order items'},
        ),
        migrations.AlterModelOptions(
            name='orderitemstatus',
            options={'verbose_name': 'Order item status', 'verbose_name_plural': 'Order item status'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=50, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='address',
            name='cep',
            field=models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.RegexValidator('^\\d+$', 'Only digit characters.')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='complement',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(max_length=50, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='address',
            name='locality',
            field=models.CharField(max_length=50, verbose_name='Locality'),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(32767)]),
        ),
        migrations.AlterField(
            model_name='address',
            name='uf',
            field=models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_tax_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_tax_value',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(32767)]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2147483647)]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(32767)]),
        ),
        migrations.AlterField(
            model_name='orderitemstatus',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=400, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2147483647)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2147483647)]),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='shippingtax',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='shippingtax',
            name='value',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(32767)]),
        ),
    ]
