# Generated by Django 5.0.6 on 2024-08-23 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_shippingfee_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteListBairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bairro')),
            ],
        ),
        migrations.CreateModel(
            name='WhiteListLocalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidade', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.localidade')),
            ],
        ),
        migrations.CreateModel(
            name='WhiteListUF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.uf')),
            ],
        ),
    ]
