# Generated by Django 5.0.6 on 2024-08-02 18:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_address_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='code',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
