# Generated by Django 5.0.6 on 2024-08-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_productcategory_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
