# Generated by Django 5.0.6 on 2024-08-08 19:46

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_productcategory_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logradouro',
            fields=[
                ('logradouro_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='cep',
            field=models.CharField(max_length=8, validators=[core.validators.cep_validator], verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='address',
            name='complement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(max_length=72),
        ),
        migrations.AlterField(
            model_name='address',
            name='locality',
            field=models.CharField(max_length=72),
        ),
        migrations.AlterField(
            model_name='address',
            name='uf',
            field=models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2, 'Digite 2 caracteres.')], verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=400, validators=[django.core.validators.MinLengthValidator(4, 'Mínimo de 4 caracteres.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, validators=[core.validators.name_validator], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30, validators=[core.validators.name_validator], verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, null=True, validators=[core.validators.phone_validator]),
        ),
    ]
