# Generated by Django 5.0.6 on 2024-08-08 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_logradouro_alter_address_address_alter_address_cep_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logradouro',
            old_name='logradouro_id',
            new_name='id',
        ),
    ]
