# Generated by Django 5.0.6 on 2024-08-08 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_logradouro_id_logradouro_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronym', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
        ),
    ]
