# Generated by Django 5.0.6 on 2024-08-09 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_uf'),
    ]

    operations = [
        migrations.AddField(
            model_name='logradouro',
            name='uf',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='core.uf'),
            preserve_default=False,
        ),
    ]
