# Generated by Django 5.0.6 on 2024-08-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_order_shipping_fee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type_code',
            field=models.CharField(default='money', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type_name',
            field=models.CharField(default='Dinheiro sem troco', max_length=30),
            preserve_default=False,
        ),
    ]
