# Generated by Django 5.0.6 on 2024-08-09 17:28

import core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_logradouro_uf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=72)),
            ],
        ),
        migrations.CreateModel(
            name='Localidade',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=72)),
                ('cep', models.CharField(max_length=8, validators=[core.validators.cep_validator])),
            ],
        ),
        migrations.CreateModel(
            name='SituacaoLocalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(32767)])),
            ],
        ),
        migrations.CreateModel(
            name='TipoLocalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='logradouro',
            name='cep',
            field=models.CharField(default=None, max_length=8, validators=[core.validators.cep_validator]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logradouro',
            name='complement',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logradouro',
            name='name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logradouro',
            name='type',
            field=models.CharField(default=None, max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logradouro',
            name='bairro',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='core.bairro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logradouro',
            name='localidade',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='core.localidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localidade',
            name='situacaolocalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.situacaolocalidade'),
        ),
    ]
