# Generated by Django 5.0.6 on 2024-08-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_bairro_localidade_situacaolocalidade_tipolocalidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situacaolocalidade',
            name='code',
        ),
        migrations.AddField(
            model_name='situacaolocalidade',
            name='definition',
            field=models.CharField(default=None, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='situacaolocalidade',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
