# Generated by Django 5.0.6 on 2024-08-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_situacaolocalidade_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situacaolocalidade',
            name='definition',
            field=models.TextField(max_length=60),
        ),
        migrations.AlterField(
            model_name='situacaolocalidade',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
