# Generated by Django 5.0.6 on 2024-10-03 18:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_order_order_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('description', models.TextField(max_length=400, validators=[django.core.validators.MinLengthValidator(4, 'Mínimo de 4 caracteres.')])),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('pizza_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.pizza')),
                ('size_name', models.CharField(max_length=40)),
                ('short_size_name', models.CharField(max_length=40)),
                ('diameter', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(32767)])),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2147483647)])),
                ('stock', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2147483647)])),
                ('stuffed_edge', models.BooleanField(default=True)),
                ('archived', models.BooleanField(default=True)),
                ('default', models.BooleanField(default=False)),
            ],
            bases=('core.pizza',),
        ),
    ]
