# Generated by Django 5.0.6 on 2024-08-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_situacaolocalidade_definition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipolocalidade',
            name='definition',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='situacaolocalidade',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
