# Generated by Django 5.0.6 on 2024-08-12 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_tipolocalidade_definition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localidade',
            name='tipolocalidade',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='core.tipolocalidade'),
            preserve_default=False,
        ),
    ]
