# Generated by Django 5.0.6 on 2024-10-03 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_pizza_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=40)),
                ('short_size_name', models.CharField(max_length=40)),
                ('diameter', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(32767)])),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2147483647)])),
                ('stock', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2147483647)])),
                ('stuffed_edge', models.BooleanField(default=True)),
                ('archived', models.BooleanField(default=True)),
                ('default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Pizza Variant',
                'verbose_name_plural': 'Pizza Variants',
            },
        ),
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
