# Generated by Django 5.0.6 on 2024-08-13 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_localidade_tipolocalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidade',
            name='situacaolocalidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.situacaolocalidade'),
        ),
    ]
