# Generated by Django 5.0.6 on 2024-10-04 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_pizzavariant_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzavariant',
            name='default',
            field=models.BooleanField(default=False, help_text='A variante que representará a pizza e será mostrada no site. Se não houver uma variante padrão a primeira variante registrada será mostrada no site. Se existir duas ou mais variantes padrões a primeira variante registrada e marcada como padrão será mostrada no site.'),
        ),
        migrations.AlterField(
            model_name='pizzavariant',
            name='short_size_name',
            field=models.CharField(blank=True, help_text='Opcional. Ex.: P, M, G', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='pizzavariant',
            name='size_name',
            field=models.CharField(help_text='Ex.: Pequena, Média, Grande', max_length=40),
        ),
        migrations.AlterField(
            model_name='pizzavariant',
            name='stock',
            field=models.PositiveIntegerField(blank=True, help_text='Opcional. Se não for preenchido, o estoque será ilimitado para pedidos. 0 representa que o estoque está vazio.', null=True, validators=[django.core.validators.MaxValueValidator(2147483647)]),
        ),
    ]
