# Generated by Django 5.0.6 on 2024-10-04 20:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_soda_sodavariant_remove_pizza_discount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sodavariant',
            options={'verbose_name': 'Variante de Pizza', 'verbose_name_plural': 'Variantes de Pizza'},
        ),
        migrations.AddField(
            model_name='soda',
            name='description',
            field=models.TextField(default='description', max_length=400, validators=[django.core.validators.MinLengthValidator(4, 'Mínimo de 4 caracteres.')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soda',
            name='name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sodavariant',
            name='archived',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sodavariant',
            name='default',
            field=models.BooleanField(default=False, help_text='A variante que representará a pizza e será mostrada no site. Se não houver uma variante padrão a primeira variante registrada será mostrada no site. Se existir duas ou mais variantes padrões a primeira variante registrada e marcada como padrão será mostrada no site.'),
        ),
        migrations.AddField(
            model_name='sodavariant',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Em decimal. Ex.: 0.1 para representar 10%. 0.0 quando não há desconto.', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='sodavariant',
            name='measure',
            field=models.CharField(default=0, help_text='Ex.: 2 Litros, 2L, 250ml', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sodavariant',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='Em inteiro. Ex.: 4999 para representar R$ 49,99', validators=[django.core.validators.MaxValueValidator(2147483647)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sodavariant',
            name='soda',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.soda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sodavariant',
            name='stock',
            field=models.PositiveIntegerField(blank=True, help_text='Opcional. Se não for preenchido, o estoque será ilimitado para pedidos. 0 representa que o estoque está vazio.', null=True, validators=[django.core.validators.MaxValueValidator(2147483647)]),
        ),
    ]
