# Generated by Django 5.0.6 on 2024-10-05 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_pizzavariant_pizza_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
    ]
