# Generated by Django 5.0.6 on 2024-10-05 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_orderitem_product'),
        ('product', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='product.product'),
            preserve_default=False,
        ),
    ]
