# Generated by Django 5.0.6 on 2024-10-17 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_orderitem_product'),
        ('product', '0005_productcategory_product_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='pizza',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='product.pizzavariant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='soda',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='product.sodavariant'),
            preserve_default=False,
        ),
    ]
