# Generated by Django 5.0.6 on 2024-10-17 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_orderitem_product'),
        ('product', '0010_remove_comboitem_product_comboitem_product_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='combo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='product.combo'),
            preserve_default=False,
        ),
    ]
