# Generated by Django 5.0.6 on 2024-10-17 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_orderitem_combo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_discount',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_price',
            new_name='price',
        ),
    ]
