# Generated by Django 5.0.6 on 2024-10-19 14:38

import core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_client_cpf_alter_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='complement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(32767)]),
        ),
        migrations.AlterField(
            model_name='client',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='client',
            name='full_name',
            field=models.CharField(default=None, max_length=60, verbose_name='Full name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='logradouro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.logradouro'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[core.validators.phone_validator], verbose_name='Number Phone'),
        ),
    ]
