# Generated by Django 5.0.6 on 2024-10-19 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_client_complement_client_number_alter_client_cpf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_address',
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.client'),
        ),
    ]
