# Generated by Django 5.0.6 on 2024-10-22 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('core', '0042_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bairro',
            name='localidade',
        ),
        migrations.RemoveField(
            model_name='logradouro',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='whitelistbairro',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='localidade',
            name='situacaolocalidade',
        ),
        migrations.RemoveField(
            model_name='localidade',
            name='tipolocalidade',
        ),
        migrations.RemoveField(
            model_name='localidade',
            name='uf',
        ),
        migrations.RemoveField(
            model_name='logradouro',
            name='localidade',
        ),
        migrations.RemoveField(
            model_name='whitelistlocalidade',
            name='localidade',
        ),
        migrations.RemoveField(
            model_name='logradouro',
            name='uf',
        ),
        migrations.AlterField(
            model_name='client',
            name='logradouro',
            field=models.ForeignKey(help_text='Pesquise pelo CEP, nome do logradouro, nome da localidade ou nome do bairro.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.logradouro'),
        ),
        migrations.RemoveField(
            model_name='whitelistuf',
            name='uf',
        ),
        migrations.AlterField(
            model_name='shippingfee',
            name='whitelistbairro',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.whitelistbairro'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.client'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Bairro',
        ),
        migrations.DeleteModel(
            name='SituacaoLocalidade',
        ),
        migrations.DeleteModel(
            name='TipoLocalidade',
        ),
        migrations.DeleteModel(
            name='Localidade',
        ),
        migrations.DeleteModel(
            name='WhiteListLocalidade',
        ),
        migrations.DeleteModel(
            name='Logradouro',
        ),
        migrations.DeleteModel(
            name='UF',
        ),
        migrations.DeleteModel(
            name='WhiteListUF',
        ),
        migrations.DeleteModel(
            name='WhiteListBairro',
        ),
    ]
