# Generated by Django 5.0.6 on 2024-10-22 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_remove_order_client_remove_order_payment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='logradouro',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
