# Generated by Django 5.0.6 on 2024-10-22 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_remove_client_logradouro_remove_user_groups_and_more'),
        ('order', '0002_alter_order_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
