# Generated by Django 5.0.6 on 2024-10-17 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_combo_comboitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Em decimal. Ex.: 0.1 para representar 10%. 0.0 quando não há desconto.', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
