# Generated by Django 5.0.6 on 2024-10-28 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_links'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Links',
            new_name='Contacts',
        ),
    ]
