# Generated by Django 5.0.6 on 2024-10-29 02:50

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_links_contacts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'contact', 'verbose_name_plural': 'contacts'},
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='x',
        ),
        migrations.AddField(
            model_name='contacts',
            name='address_link',
            field=models.URLField(default=None, verbose_name='Address link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='address_text',
            field=models.CharField(default=None, max_length=30, verbose_name='Address text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='email',
            field=models.EmailField(default=None, max_length=255, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='facebook_link',
            field=models.URLField(default=None, verbose_name='Facebook link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='instagram_link',
            field=models.URLField(default=None, verbose_name='Instagram link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='linkedin_link',
            field=models.URLField(default=None, verbose_name='LinkedIn link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='phone_number',
            field=models.CharField(default=None, max_length=11, validators=[apps.core.validators.phone_validator, django.core.validators.MinLengthValidator(10, 'Minimum of 10 characters.')], verbose_name='Telephone number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='whatsapp_message',
            field=models.URLField(default=None, max_length=100, verbose_name='WhatsApp message'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='whatsapp_number',
            field=models.CharField(default=None, max_length=11, validators=[apps.core.validators.phone_validator, django.core.validators.MinLengthValidator(11, 'Minimum of 11 characters.')], verbose_name='WhatsApp number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='x_link',
            field=models.URLField(default=None, verbose_name='X link'),
            preserve_default=False,
        ),
    ]
