# Generated by Django 5.0.6 on 2024-10-29 17:16

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_contacts_options_remove_contacts_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='whatsapp_number',
            field=models.CharField(max_length=15, validators=[apps.core.validators.phone_validator], verbose_name='WhatsApp number'),
        ),
    ]
