# Generated by Django 5.0.6 on 2024-10-31 15:50

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_contacts_whatsapp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[apps.core.validators.cpf_validator], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[apps.core.validators.phone_validator], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[apps.core.validators.phone_validator], verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='whatsapp_message',
            field=models.CharField(max_length=100, verbose_name='WhatsApp message'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='whatsapp_number',
            field=models.CharField(max_length=11, validators=[apps.core.validators.cellphone_number], verbose_name='WhatsApp number'),
        ),
    ]
