# Generated by Django 5.0.6 on 2024-10-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_client_cpf_alter_client_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='whatsapp_message',
            field=models.TextField(max_length=100, verbose_name='WhatsApp message'),
        ),
    ]
