# Generated by Django 5.0.6 on 2024-10-31 16:03

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_contacts_whatsapp_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='address_link',
            field=models.URLField(blank=True, null=True, verbose_name='Address link'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='address_text',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Address text'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='facebook_link',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook link'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='instagram_link',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram link'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn link'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[apps.core.validators.phone_validator], verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='whatsapp_message',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='WhatsApp message'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[apps.core.validators.cellphone_number], verbose_name='WhatsApp number'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='x_link',
            field=models.URLField(blank=True, null=True, verbose_name='X link'),
        ),
    ]
