# Generated by Django 5.0.6 on 2024-10-31 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_contacts_address_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='google_maps',
            field=models.URLField(blank=True, null=True, verbose_name='Google Maps'),
        ),
    ]
