# Generated by Django 5.0.6 on 2024-10-31 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_contacts_google_maps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='google_maps',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='Google Maps'),
        ),
    ]
