# Generated by Django 5.0.6 on 2024-10-31 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_contacts_google_maps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='address_text',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Address text'),
        ),
    ]
