# Generated by Django 5.0.6 on 2024-10-31 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_openinghours'),
    ]

    operations = [
        migrations.AddField(
            model_name='openinghours',
            name='duration',
            field=models.DurationField(default=None),
            preserve_default=False,
        ),
    ]
