# Generated by Django 5.0.6 on 2024-11-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_openinghours_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openinghours',
            name='duration',
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='day_from',
            field=models.CharField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], max_length=1),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='day_to',
            field=models.CharField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], max_length=1),
        ),
    ]
