# Generated by Django 5.0.6 on 2024-11-01 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_remove_openinghours_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openinghours',
            name='contacts',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.contacts'),
            preserve_default=False,
        ),
    ]
