# Generated by Django 5.0.6 on 2024-11-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_openinghours_contacts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openinghours',
            options={'verbose_name': 'opening hours', 'verbose_name_plural': 'opening hours'},
        ),
        migrations.AddField(
            model_name='openinghours',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='day_from',
            field=models.CharField(blank=True, choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='day_to',
            field=models.CharField(blank=True, choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='hour_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='hour_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
