# Generated by Django 5.0.6 on 2024-11-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_openinghours_options_openinghours_closed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghours',
            name='closed',
            field=models.BooleanField(default=False, help_text='If this field was marked, the other fields is not required.'),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='day_from',
            field=models.CharField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
