# Generated by Django 5.0.6 on 2024-11-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_openinghours_closed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openinghours',
            old_name='day_to',
            new_name='final_day',
        ),
        migrations.RenameField(
            model_name='openinghours',
            old_name='hour_from',
            new_name='final_hour',
        ),
        migrations.RenameField(
            model_name='openinghours',
            old_name='day_from',
            new_name='inital_day',
        ),
        migrations.RemoveField(
            model_name='openinghours',
            name='hour_to',
        ),
        migrations.AddField(
            model_name='openinghours',
            name='inital_hour',
            field=models.TimeField(blank=True, null=True, verbose_name='test'),
        ),
    ]
