# Generated by Django 5.0.6 on 2024-11-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_rename_day_to_openinghours_final_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghours',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='Closed'),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='final_day',
            field=models.CharField(blank=True, choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], max_length=1, null=True, verbose_name='Final day'),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='final_hour',
            field=models.TimeField(blank=True, null=True, verbose_name='Final hour'),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='inital_day',
            field=models.CharField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], max_length=1, verbose_name='Initial day'),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='inital_hour',
            field=models.TimeField(blank=True, null=True, verbose_name='Initial hour'),
        ),
    ]
