# Generated by Django 5.0.6 on 2024-11-23 18:19

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_openinghours_closed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[apps.core.validators.cpf_validator], verbose_name='CPF'),
        ),
    ]
