# Generated by Django 5.0.6 on 2024-12-19 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_user_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='google_maps',
        ),
    ]
