# Generated by Django 5.0.6 on 2025-01-03 18:21

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_remove_contacts_google_maps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[apps.core.validators.phone_validator]),
        ),
    ]
