# Generated by Django 5.0.6 on 2025-01-04 15:19

import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_rename_owner_user_owned_by_user_is_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'client', 'verbose_name_plural': 'clients'},
        ),
        migrations.AlterField(
            model_name='client',
            name='complement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='complement'),
        ),
        migrations.AlterField(
            model_name='client',
            name='full_name',
            field=models.CharField(max_length=60, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(32767)], verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[apps.core.validators.phone_validator], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='address_link',
            field=models.URLField(blank=True, null=True, verbose_name='address link'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='address_text',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='address text'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='facebook_link',
            field=models.URLField(blank=True, null=True, verbose_name='facebook link'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='instagram_link',
            field=models.URLField(blank=True, null=True, verbose_name='instagram link'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True, verbose_name='linkedIn link'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[apps.core.validators.phone_validator], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='whatsapp_message',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='whatsApp message'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[apps.core.validators.cellphone_number], verbose_name='whatsApp number'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='x_link',
            field=models.URLField(blank=True, null=True, verbose_name='x link'),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='closed'),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='contacts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.contacts', verbose_name='contacts'),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='final_day',
            field=models.CharField(blank=True, choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], max_length=1, null=True, verbose_name='final day'),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='final_hour',
            field=models.TimeField(blank=True, null=True, verbose_name='final hour'),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='inital_day',
            field=models.CharField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], max_length=1, verbose_name='initial day'),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='inital_hour',
            field=models.TimeField(blank=True, null=True, verbose_name='initial hour'),
        ),
        migrations.AlterField(
            model_name='user',
            name='owned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='owned by'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[apps.core.validators.phone_validator], verbose_name='phone number'),
        ),
    ]
