# Generated by Django 5.0.6 on 2024-08-14 17:14

import apps.core.validators
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
import re
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localidade',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=72)),
                ('cep', models.CharField(max_length=8, validators=[apps.core.validators.cep_validator])),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Order item status',
                'verbose_name_plural': 'Order item status',
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2147483647)])),
                ('description', models.TextField(max_length=400, validators=[django.core.validators.MinLengthValidator(4, 'Mínimo de 4 caracteres.')])),
                ('stock', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2147483647)])),
                ('archived', models.BooleanField(default=False)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='ShippingTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('value', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(32767)])),
            ],
        ),
        migrations.CreateModel(
            name='SituacaoLocalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.TextField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TipoLocalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1)),
                ('definition', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='UF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronym', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(help_text='Required. 15 characters or fewer. Letters, numbers and @/./+/-/_ characters', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z0-9_.-]+$'), 'Enter a valid username.', 'invalid')], verbose_name='username')),
                ('first_name', models.CharField(max_length=30, validators=[apps.core.validators.name_validator], verbose_name='first name')),
                ('last_name', models.CharField(max_length=30, validators=[apps.core.validators.name_validator], verbose_name='last name')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_trusty', models.BooleanField(default=False, help_text='Designates whether this user has confirmed his account.', verbose_name='trusty')),
                ('phone', models.CharField(max_length=11, null=True, validators=[apps.core.validators.phone_validator])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=72)),
                ('localidade', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.localidade')),
            ],
        ),
        migrations.CreateModel(
            name='Logradouro',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('complement', models.CharField(max_length=100, null=True)),
                ('cep', models.CharField(max_length=8, validators=[apps.core.validators.cep_validator])),
                ('type', models.CharField(max_length=36)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.bairro')),
                ('uf', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.uf')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(32767)])),
                ('complement', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, unique=True)),
                ('logradouro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.logradouro')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_tax_name', models.CharField(max_length=40, null=True)),
                ('shipping_tax_value', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(32767)])),
                ('created', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('received_date', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.paymenttype')),
                ('shipping_tax', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.shippingtax')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_price', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2147483647)])),
                ('product_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(32767)])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.order')),
                ('order_item_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='core.orderitemstatus')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.product')),
            ],
            options={
                'verbose_name': 'Order item',
                'verbose_name_plural': 'Order items',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.productcategory'),
        ),
        migrations.AddField(
            model_name='localidade',
            name='situacaolocalidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.situacaolocalidade'),
        ),
        migrations.AddField(
            model_name='localidade',
            name='tipolocalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.tipolocalidade'),
        ),
    ]
