# Generated by Django 5.0.6 on 2024-08-15 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_bairro_localidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='logradouro',
            name='localidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.localidade'),
        ),
        migrations.AlterField(
            model_name='logradouro',
            name='bairro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bairro'),
        ),
    ]
