# Generated by Django 5.0.6 on 2024-08-16 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_logradouro_localidade_alter_logradouro_bairro'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingTax',
            new_name='ShippingFee',
        ),
    ]
