# Generated by Django 5.0.6 on 2024-08-16 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_shippingtax_shippingfee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_tax',
            new_name='shipping_fee',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_tax_name',
            new_name='shipping_fee_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_tax_value',
            new_name='shipping_fee_value',
        ),
    ]
