# Generated by Django 5.0.6 on 2024-08-23 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_whitelistbairro_whitelistlocalidade_whitelistuf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingfee',
            name='bairro',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bairro'),
        ),
    ]
