# Generated by Django 5.0.6 on 2024-08-26 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_shippingfee_bairro'),
    ]

    operations = [
        migrations.AddField(
            model_name='localidade',
            name='uf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.uf'),
        ),
    ]
