# Generated by Django 5.0.6 on 2024-08-26 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_localidade_uf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingfee',
            name='bairro',
        ),
        migrations.AddField(
            model_name='shippingfee',
            name='whitelistbairro',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.whitelistbairro'),
        ),
    ]
