# Generated by Django 5.0.6 on 2024-08-27 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_bairro_id_alter_localidade_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_fee_name',
        ),
    ]
