# Generated by Django 5.0.6 on 2024-08-28 18:14

import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_order_payment_type_code_order_payment_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_number', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(32767)])),
                ('address_complement', models.CharField(blank=True, max_length=100, null=True)),
                ('uf_acronym', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2)])),
                ('logradouro_cep', models.CharField(max_length=8, validators=[apps.core.validators.cep_validator])),
                ('logradouro_name', models.CharField(max_length=100)),
                ('logradouro_type', models.CharField(max_length=36)),
                ('localidade_name', models.CharField(max_length=72)),
                ('bairro_name', models.CharField(max_length=72)),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='order_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.orderaddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_address',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='core.orderaddress'),
            preserve_default=False,
        ),
    ]
