# Generated by Django 5.0.6 on 2024-08-29 15:04

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_orderaddress_address_order_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderaddress',
            name='address_complement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complement'),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='address_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(32767)], verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='bairro_name',
            field=models.CharField(max_length=72, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='localidade_name',
            field=models.CharField(max_length=72, verbose_name='Localidade'),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='logradouro_cep',
            field=models.CharField(max_length=8, validators=[apps.core.validators.cep_validator], verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='logradouro_name',
            field=models.CharField(max_length=100, verbose_name='Nome do logradouro'),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='logradouro_type',
            field=models.CharField(max_length=36, verbose_name='Tipo do logradouro'),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='uf_acronym',
            field=models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='UF'),
        ),
    ]
