# Generated by Django 5.0.6 on 2024-08-30 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_orderaddress_address_complement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.orderaddress'),
        ),
    ]
