# Generated by Django 5.0.6 on 2024-10-03 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_pizzavariant_delete_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzavariant',
            name='pizza',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.pizza'),
            preserve_default=False,
        ),
    ]
