# Generated by Django 5.0.6 on 2024-10-04 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_pizzavariant_pizza'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizzavariant',
            options={'verbose_name': 'Variante de Pizza', 'verbose_name_plural': 'Variantes de Pizza'},
        ),
        migrations.AlterField(
            model_name='pizzavariant',
            name='diameter',
            field=models.PositiveSmallIntegerField(default=0, help_text='Em centimetros', validators=[django.core.validators.MaxValueValidator(32767)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pizzavariant',
            name='price',
            field=models.PositiveIntegerField(help_text='Em inteiro. Ex.: 4999 para representar R$ 49,99', validators=[django.core.validators.MaxValueValidator(2147483647)]),
        ),
        migrations.AlterField(
            model_name='pizzavariant',
            name='short_size_name',
            field=models.CharField(blank=True, help_text='Ex.: P, M, G', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='pizzavariant',
            name='size_name',
            field=models.CharField(help_text='Ex.: Pequena, Média, Grante', max_length=40),
        ),
        migrations.AlterField(
            model_name='pizzavariant',
            name='stock',
            field=models.PositiveIntegerField(blank=True, help_text='Se não for preenchido, o estoque será ilimitado para pedidos.', null=True, validators=[django.core.validators.MaxValueValidator(2147483647)]),
        ),
    ]
