# Generated by Django 5.0.6 on 2024-10-04 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_pizzavariant_default_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SodaVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='discount',
        ),
        migrations.AddField(
            model_name='pizzavariant',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Em decimal. Ex.: 0.1 para representar 10%. 0.0 quando não há desconto.', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
