# Generated by Django 5.0.6 on 2024-10-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_sodavariant_options_soda_description_soda_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizzavariant',
            options={'verbose_name': 'Variante de pizza', 'verbose_name_plural': 'Variantes de pizza'},
        ),
        migrations.AlterModelOptions(
            name='soda',
            options={'verbose_name': 'Refrigerante', 'verbose_name_plural': 'Refrigerantes'},
        ),
        migrations.AlterModelOptions(
            name='sodavariant',
            options={'verbose_name': 'Variante de refrigerante', 'verbose_name_plural': 'Variantes de refrigerante'},
        ),
        migrations.AlterField(
            model_name='sodavariant',
            name='default',
            field=models.BooleanField(default=False, help_text='A variante que representará o refrigerante e será mostrada no site. Se não houver uma variante padrão a primeira variante registrada será mostrada no site. Se existir duas ou mais variantes padrões a primeira variante registrada e marcada como padrão será mostrada no site.'),
        ),
    ]
