# Generated by Django 5.0.6 on 2024-10-05 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_pizzavariant_options_alter_soda_options_and_more'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzavariant',
            name='pizza',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_category',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='product.product'),
        ),
        migrations.RemoveField(
            model_name='sodavariant',
            name='soda',
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='PizzaVariant',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Soda',
        ),
        migrations.DeleteModel(
            name='SodaVariant',
        ),
    ]
