# Generated by Django 5.0.6 on 2024-10-05 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_orderitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
    ]
