# Generated by Django 5.0.6 on 2024-10-17 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_orderitem_pizza_orderitem_soda'),
        ('product', '0006_remove_product_archived_remove_product_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='pizza',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='soda',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='product.product'),
            preserve_default=False,
        ),
    ]
