# Generated by Django 5.0.6 on 2024-10-17 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_orderitem_pizza_remove_orderitem_soda_and_more'),
        ('product', '0007_remove_pizzavariant_pizza_remove_sodavariant_soda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='product.productvariant'),
        ),
    ]
