# Generated by Django 5.0.6 on 2024-10-19 04:33

import apps.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_remove_order_user_order_client_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client_name',
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=60, null=True)),
                ('phone', models.CharField(max_length=11, null=True, validators=[apps.core.validators.phone_validator])),
                ('logradouro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.logradouro')),
            ],
        ),
    ]
