# Generated by Django 5.0.6 on 2024-10-19 04:38

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_remove_order_client_name_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[apps.core.validators.phone_validator]),
        ),
    ]
