# Generated by Django 5.0.6 on 2024-10-22 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_remove_bairro_localidade_remove_logradouro_bairro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_fee',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='OrderAddress',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='combo',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order_item_status',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shippingfee',
            name='whitelistbairro',
        ),
        migrations.DeleteModel(
            name='PaymentType',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItemStatus',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='ShippingFee',
        ),
    ]
