# Generated by Django 5.0.6 on 2024-10-28 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialLinks',
        ),
    ]
