# Generated by Django 5.0.6 on 2024-10-22 18:28

import apps.core.validators
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('core', '0044_remove_order_client_remove_order_payment_type_and_more'),
        ('product', '0010_remove_comboitem_product_comboitem_product_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_number', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(32767)], verbose_name='Number')),
                ('address_complement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complement')),
                ('uf_acronym', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='UF')),
                ('logradouro_cep', models.CharField(max_length=8, validators=[apps.core.validators.cep_validator], verbose_name='CEP')),
                ('logradouro_name', models.CharField(max_length=100, verbose_name='Nome do logradouro')),
                ('logradouro_type', models.CharField(max_length=36, verbose_name='Tipo do logradouro')),
                ('localidade_name', models.CharField(max_length=72, verbose_name='Localidade')),
                ('bairro_name', models.CharField(max_length=72, verbose_name='Bairro')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Order item status',
                'verbose_name_plural': 'Order item status',
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type_name', models.CharField(max_length=30)),
                ('payment_type_code', models.CharField(max_length=30)),
                ('shipping_fee_value', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(32767)])),
                ('created', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.client')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='order.paymenttype')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2147483647)])),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('quantity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(32767)])),
                ('combo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='product.combo')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='order.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='product.productvariant')),
                ('order_item_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='order.orderitemstatus')),
            ],
            options={
                'verbose_name': 'Order item',
                'verbose_name_plural': 'Order items',
            },
        ),
        migrations.CreateModel(
            name='ShippingFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(32767)])),
                ('is_default', models.BooleanField(default=False, verbose_name='Default')),
                ('whitelistbairro', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.whitelistbairro')),
            ],
            options={
                'verbose_name': 'Shipping fee',
                'verbose_name_plural': 'Shipping fees',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='order.shippingfee'),
        ),
    ]
