# Generated by Django 5.0.6 on 2024-11-15 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingfee',
            name='whitelistbairro',
        ),
    ]
