# Generated by Django 5.0.6 on 2024-11-16 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0008_alter_whitelist_options'),
        ('order', '0003_remove_shippingfee_whitelistbairro'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingfee',
            name='bairro',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.bairro'),
        ),
    ]
