# Generated by Django 5.0.6 on 2024-12-02 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0013_alter_whitelist_bairros_alter_whitelist_localidades_and_more'),
        ('order', '0008_alter_shippingfee_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingfee',
            name='bairro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.bairro'),
        ),
        migrations.AlterUniqueTogether(
            name='shippingfee',
            unique_together={('user', 'bairro')},
        ),
    ]
