# Generated by Django 5.0.6 on 2024-12-02 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_shippingfee_bairro_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shippingfee',
            unique_together=set(),
        ),
    ]
