# Generated by Django 5.0.6 on 2024-12-02 19:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0013_alter_whitelist_bairros_alter_whitelist_localidades_and_more'),
        ('order', '0010_alter_shippingfee_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shippingfee',
            unique_together={('bairro', 'user')},
        ),
    ]
