# Generated by Django 5.0.6 on 2024-12-06 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_shippingfee_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shippingfee',
            unique_together=set(),
        ),
    ]
