# Generated by Django 5.0.6 on 2024-12-08 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_alter_order_user_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderAddress',
        ),
    ]
