# Generated by Django 5.0.6 on 2024-12-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_delete_orderaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_type_code',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
