# Generated by Django 5.0.6 on 2024-12-14 18:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_remove_order_payment_type_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='change_to',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(32767)], verbose_name='Troco para'),
        ),
    ]
