# Generated by Django 5.0.6 on 2024-12-17 17:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_order_change_to'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItemStatus',
            new_name='OrderStatus',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order_item_status',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='order.orderstatus'),
        ),
        migrations.AlterField(
            model_name='order',
            name='change_to',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(32767)], verbose_name='Troco para'),
        ),
    ]
