# Generated by Django 5.0.6 on 2024-12-19 17:31

import django.core.validators
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_rename_orderitemstatus_orderstatus_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderStatus',
            new_name='Status',
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Status'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_status',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(blank=True, db_default=django.db.models.functions.datetime.Now(), null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2147483647)]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(32767)]),
        ),
    ]
