# Generated by Django 5.0.6 on 2025-01-04 15:19

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_rename_orderstatus_status_alter_status_options_and_more'),
        ('product', '0040_alter_comboitem_options_alter_category_name_and_more'),
        ('user', '0027_alter_client_options_alter_client_complement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'order item', 'verbose_name_plural': 'order items'},
        ),
        migrations.AlterModelOptions(
            name='paymenttype',
            options={'verbose_name': 'payment type', 'verbose_name_plural': 'payment types'},
        ),
        migrations.AlterModelOptions(
            name='shippingfee',
            options={'verbose_name': 'shipping fee', 'verbose_name_plural': 'shipping fees'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'status', 'verbose_name_plural': 'status'},
        ),
        migrations.AlterField(
            model_name='order',
            name='change_to',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(32767)], verbose_name='change to'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.client', verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(blank=True, db_default=django.db.models.functions.datetime.Now(), null=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='order.paymenttype', verbose_name='payment type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type_name',
            field=models.CharField(max_length=30, verbose_name='payment type name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='received_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='received date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_fee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='order.shippingfee', verbose_name='shipping fee'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_fee_value',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(32767)], verbose_name='shipping fee value'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='order.status', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_owner', to=settings.AUTH_USER_MODEL, verbose_name='user owner'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_request', to=settings.AUTH_USER_MODEL, verbose_name='user request'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='product.combo', verbose_name='combo'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='order.order', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2147483647)], verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productvariant', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(32767)], verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='name',
            field=models.CharField(max_length=30, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='shippingfee',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='default'),
        ),
        migrations.AlterField(
            model_name='shippingfee',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='shippingfee',
            name='value',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(32767)], verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='status',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=30, verbose_name='name'),
        ),
    ]
