# Generated by Django 5.0.6 on 2025-05-29 19:22

import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0014_alter_address_options_alter_whitelist_options_and_more'),
        ('order', '0023_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='address.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='address_complement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='complement'),
        ),
        migrations.AddField(
            model_name='order',
            name='address_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(32767)], verbose_name='number'),
        ),
        migrations.AddField(
            model_name='order',
            name='bairro_name',
            field=models.CharField(default='', max_length=72, verbose_name='bairro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='', max_length=255, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default=0, max_length=60, validators=[apps.core.validators.name_validator], verbose_name='full name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='logradouro_cep',
            field=models.CharField(default='', max_length=8, validators=[apps.core.validators.cep_validator], verbose_name='cep'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='logradouro_name',
            field=models.CharField(default='', max_length=100, verbose_name='address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[apps.core.validators.phone_validator], verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='order',
            name='uf_acronym',
            field=models.CharField(default='', max_length=2, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='state'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type_name',
            field=models.CharField(max_length=30, verbose_name='payment type'),
        ),
    ]
