# Generated by Django 5.0.6 on 2025-05-29 20:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_order_address_order_address_complement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='option1',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='option'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='option2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='option'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='option3',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='option'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='option4',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='option'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='option5',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='option'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price1',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(32767)], verbose_name='price'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price2',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(32767)], verbose_name='price'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price3',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(32767)], verbose_name='price'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price4',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(32767)], verbose_name='price'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price5',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(32767)], verbose_name='price'),
        ),
    ]
