# Generated by Django 5.0.6 on 2025-05-30 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_orderitem_option1_orderitem_option2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2147483647)], verbose_name='total'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2147483647)], verbose_name='total'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(max_length=60, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='option1',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='option name'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='option2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='option name'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='option3',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='option name'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='option4',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='option name'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='option5',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='option name'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price1',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(32767)], verbose_name='option price'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price2',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(32767)], verbose_name='option price'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price3',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(32767)], verbose_name='option price'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price4',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(32767)], verbose_name='option price'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price5',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(32767)], verbose_name='option price'),
        ),
    ]
