# Generated by Django 5.0.6 on 2025-05-30 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_order_total_orderitem_total_alter_order_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='total',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2147483647)], verbose_name='total'),
        ),
    ]
