# Generated by Django 5.0.6 on 2024-10-22 17:54

import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localidade',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=72)),
                ('cep', models.CharField(max_length=8, validators=[apps.core.validators.cep_validator])),
            ],
        ),
        migrations.CreateModel(
            name='SituacaoLocalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.TextField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TipoLocalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1)),
                ('definition', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='UF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronym', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
        ),
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=72)),
                ('localidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.localidade')),
            ],
        ),
        migrations.AddField(
            model_name='localidade',
            name='situacaolocalidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='address.situacaolocalidade'),
        ),
        migrations.AddField(
            model_name='localidade',
            name='tipolocalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='address.tipolocalidade'),
        ),
        migrations.CreateModel(
            name='Logradouro',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('complement', models.CharField(max_length=100, null=True)),
                ('cep', models.CharField(max_length=8, validators=[apps.core.validators.cep_validator])),
                ('type', models.CharField(max_length=36)),
                ('bairro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.bairro')),
                ('localidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.localidade')),
                ('uf', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='address.uf')),
            ],
        ),
        migrations.AddField(
            model_name='localidade',
            name='uf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.uf'),
        ),
        migrations.CreateModel(
            name='WhiteListBairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.bairro')),
            ],
        ),
        migrations.CreateModel(
            name='WhiteListLocalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidade', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.localidade')),
            ],
        ),
        migrations.CreateModel(
            name='WhiteListUF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.uf')),
            ],
        ),
    ]
