# Generated by Django 5.0.6 on 2024-11-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_white'),
    ]

    operations = [
        migrations.RenameField(
            model_name='white',
            old_name='uf',
            new_name='ufs',
        ),
        migrations.AddField(
            model_name='white',
            name='bairros',
            field=models.ManyToManyField(to='address.bairro'),
        ),
        migrations.AddField(
            model_name='white',
            name='localidades',
            field=models.ManyToManyField(to='address.localidade'),
        ),
    ]
