# Generated by Django 5.0.6 on 2024-11-15 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_whitelist_delete_white'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhiteList',
        ),
    ]
