# Generated by Django 5.0.6 on 2024-11-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_delete_whitelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairros', models.ManyToManyField(blank=True, null=True, to='address.bairro')),
                ('localidades', models.ManyToManyField(blank=True, null=True, to='address.localidade')),
                ('ufs', models.ManyToManyField(blank=True, null=True, to='address.uf')),
            ],
        ),
    ]
