# Generated by Django 5.0.6 on 2024-11-15 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_whitelist'),
        ('order', '0003_remove_shippingfee_whitelistbairro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whitelistlocalidade',
            name='localidade',
        ),
        migrations.RemoveField(
            model_name='whitelistuf',
            name='uf',
        ),
        migrations.DeleteModel(
            name='WhiteListBairro',
        ),
        migrations.DeleteModel(
            name='WhiteListLocalidade',
        ),
        migrations.DeleteModel(
            name='WhiteListUF',
        ),
    ]
