# Generated by Django 5.0.6 on 2024-11-16 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0007_remove_whitelistlocalidade_localidade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whitelist',
            options={'verbose_name': 'whiteList', 'verbose_name_plural': 'whiteLists'},
        ),
    ]
