# Generated by Django 5.0.6 on 2024-12-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0012_whitelist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitelist',
            name='bairros',
            field=models.ManyToManyField(blank=True, to='address.bairro'),
        ),
        migrations.AlterField(
            model_name='whitelist',
            name='localidades',
            field=models.ManyToManyField(blank=True, to='address.localidade'),
        ),
        migrations.AlterField(
            model_name='whitelist',
            name='ufs',
            field=models.ManyToManyField(blank=True, to='address.uf'),
        ),
    ]
