# Generated by Django 5.0.6 on 2025-01-04 15:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0013_alter_whitelist_bairros_alter_whitelist_localidades_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'address', 'verbose_name_plural': 'addresses'},
        ),
        migrations.AlterModelOptions(
            name='whitelist',
            options={'verbose_name': 'white list', 'verbose_name_plural': 'white lists'},
        ),
        migrations.AlterField(
            model_name='address',
            name='complement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='complement'),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(32767)], verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='bairro',
            name='name',
            field=models.CharField(max_length=72, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='localidade',
            name='name',
            field=models.CharField(max_length=72, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='logradouro',
            name='complement',
            field=models.CharField(max_length=100, null=True, verbose_name='complement'),
        ),
        migrations.AlterField(
            model_name='logradouro',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='logradouro',
            name='type',
            field=models.CharField(max_length=36, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='tipolocalidade',
            name='code',
            field=models.CharField(max_length=1, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='tipolocalidade',
            name='definition',
            field=models.CharField(max_length=15, verbose_name='definition'),
        ),
        migrations.AlterField(
            model_name='uf',
            name='acronym',
            field=models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='acronym'),
        ),
        migrations.AlterField(
            model_name='whitelist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
